variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - build_image
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/customJacocoReportDir/test/jacocoTestReport.xml
      - build/test-results/test/

build_image:
  stage: build_image
#  image: docker:24.0.5
  script:
    - docker-compose build
    - docker-compose up -d

sonar:
  stage: sonar
  script:
    - ./gradlew sonar test jacocoTestReport