variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - build_image
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

build_image:
  stage: build_image
#  image: docker:24.0.5
  script:
    - docker-compose build
    - docker-compose up -d
  artifacts:
    paths:
      - build/libs/*.jar

sonar:
  stage: sonar
  script:
    - ./gradlew sonar test jacocoTestReport