variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: kaloyankerr/fitsphere-backend
  IMAGE_TAG: latest

stages:
  - build
  - test
  - build_image
  - sonar

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - F jacocoTestReport
  artifacts:
    paths:
      - build/customJacocoReportDir/test/jacocoTestReport.xml
      - build/test-results/test/
    expire_in: 1 week

build_image:
  stage: build_image
  services:
    - docker:24.0.5-dind
  before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker tag fitsphere-backend ${IMAGE_NAME}:${IMAGE_TAG}
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}

sonar:
  stage: sonar
  script:
    - ./gradlew sonar
  dependencies:
    - test

