variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"

stages:
  - build
  - test
  - build_image
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/customJacocoReportDir/test/jacocoTestReport.xml
      - build/test-results/test/

build_image:
  stage: build_image
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - docker-compose build --no-cache
    - docker-compose up -d

sonar:
  stage: sonar
  script:
    - ./gradlew sonar
  dependencies:
    - test
