variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"

stages:
  - build
  - test
  - build_image
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/customJacocoReportDir/test/jacocoTestReport.xml
      - build/test-results/test/

build_image:
  stage: build_image
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - docker-compose build --no-cache
    - docker-compose up -d

    # Login to Docker Hub
    - echo "}A7g-BCi-YLwr]]" | docker login -u "kaloyankerr" --password-stdin

    # Tag and push the Docker image to Docker Hub
    # Assuming `web` is the name of the service in your docker-compose.yml
    - docker tag fitsphere-backend:latest kaloyankerr/fitsphere-backend:latest

    - docker push kaloyankerr/fitsphere-backend:latest
  only:
    - master


sonar:
  stage: sonar
  script:
    - ./gradlew sonar
  dependencies:
    - test
