version: '3.8'

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0.37
    container_name: fitsphere-database
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=${DB_DATASOURCE_URL}
    ports:
      - 3307:3306

    networks:
      - my_network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: fitsphere-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - my_network
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
